ISO_NAME=`ls {iso_dir}`
ENV_NAME=MOS_CI_"$ISO_NAME"
ISO_ID=`echo "$ISO_NAME" | cut -f3 -d-`
ISO_PATH="${ISO_DIR}/${ISO_NAME}"

echo "ENV_NAME=$ENV_NAME" > "$ENV_INJECT_PATH"
echo "ISO_ID=$ISO_ID" >> "$ENV_INJECT_PATH"
echo "ISO_PATH=$ISO_PATH" >> "$ENV_INJECT_PATH"